# Updated yaml file tested on Ubuntu 22.04 in October 2024
name: latentfusion
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aggdraw
  - attrs
  - av
  - backcall
  - blas
  - bleach
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - chardet
  - cryptography
  - cudatoolkit
  - cycler
  - dbus
  - decorator
  - defusedxml
  - entrypoints
  - expat
  - ffmpeg
  - fontconfig
  - freeglut
  - freetype
  - gettext
  - giflib
  - glib
  - gmp
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jasper
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver
  - lame
  - libclang
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libiconv
  - libllvm9
  - libopencv
  - libpng
  - libsodium
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp
  - libxcb
  - libxkbcommon
  - libxml2
  - llvm-openmp
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mistune
  - mkl
  - nbconvert
  - nbformat
  - ncurses
  - nettle
  - ninja
  - nodejs
  - notebook
  - nspr
  - nss
  - numpy=1.24
  - olefile
  - opencv
  - openh264
  - openssl
  - pandoc
  - pandocfilters
  - parso
  - pcre
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pixman
  - prometheus_client
  - prompt-toolkit
  - pthread-stubs
  - ptyprocess
  - py-opencv
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrsistent
  - pysocks
  - pyzmq
  - qt
  - readline
  - requests
  - send2trash
  - setuptools
  - six
  - sqlite
  - terminado
  - testpath
  - tk
  - torchvision
  - tornado
  - traitlets
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - x264
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
    - absl-py
    - cachetools
    - colorama
    - cython
    - filelock
    - freetype-py
    - google-auth
    - google-auth-oauthlib
    - grpcio
    - imageio
    - joblib
    - jsonpatch
    - jsonpointer
    - markdown
    - networkx
    - nose
    - oauthlib
    - opencv-python==4.10
    - pandas
    - plyfile
    - protobuf
    - pyasn1
    - pyasn1-modules
    - pyassimp
    - pyglet
    - pyopengl
    - pyopengl-accelerate
    - pyqt5-sip
    - pyqtwebengine
    - pyquaternion
    - pyrender
    - pytz
    - pywavelets
    - requests-oauthlib
    - rsa
    - scikit-image
    - scikit-learn
    - scipy
    - seaborn
    - structlog
    - tabulate
    - tensorboard
    - tensorboard-plugin-wit
    - tensorboardx
    - toml
    - torchfile
    - torchnet
    - tqdm
    - transforms3d
    - trimesh
    - ujson
    - urllib3
    - visdom
    - websocket-client
    - werkzeug


